### ISSUE TITLE
vegetarian status shouldn't be undefined

### ISSUE THREAD

**Issue by sbburton** [sbburton/foodMacroChecker#2]
.js showIngredients() function should be altered so that all undefined cells have different text. go nuts.

**Comment by Khusyasy** [comment]
Hello @sbburton 

I'm interested to help with this issue, can you give me more info on what should I do?

**Comment by sbburton** [comment]
Hello Khusyasy! Certainly. I've just been learning more about versioning control and this was to help me understand opening issues.  If you would like to help, I want all ingredients that have an "undefined" vegetarian status to instead have the text "unknown"

**Comment by Khusyasy** [comment]
Sure, I will look into this issue and create a pull request as soon as possible!

**Comment by sbburton** [comment]
looks great, thanks!
